### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/pure_func#1]
@winged könntest Du das bitte reviewen? Das Ding sollte richtig perfekt werden. Hab extra kein pyproject benutzt, da es so klein ist.

**Comment by sliverc** [comment]
Thumbs up for the clear documentation and implementation.

Just some comments and ideas:

* Wouldn't it be better to combine checking context manager and checked decorator into one function?
https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator
https://github.com/adfinis-sygroup/pure_func/blob/master/pure_func.py#L102
* Any reasons that you use two underscores for pure_check and sampling_check global vars? Shouldn't it be just one to avoid issues?
https://github.com/adfinis-sygroup/pure_func/blob/master/pure_func.py#L89
* It is not clear to me why you use modulo 13 here
https://github.com/adfinis-sygroup/pure_func/blob/master/pure_func.py#L199

**Comment by ghost** [comment]
* ContextDecorator, cool I'll switch to it
* Well I read up on the double-underscores and they seem to indicate: Never ever touch. And double-underscores are better hidden in REPLS. But in the end it doesn't matter. I switch them back to one underscore.
* It is a nice prime around 10. There should be some delay and it shouldn't be 10, because people tend to use 10 in their logic, so sampling might always catch "good"-states. Should I write that as a comment or what do you think?

**Comment by sliverc** [comment]
Yep it would be good to write modulo 13 idea into a comment

**Comment by ghost** [comment]
Note to me: Implement ContextDecorator as checked(), change the documentation, but keep an alias to checking to we don't break existing code.

**Comment by ghost** [comment]
Stale, close
