### ISSUE TITLE
Add clear_on_gc to pure_check and pure_sampling?

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/pure_func#4]
* Clears the history on gc like gcd_lru_cache clears the cache.
* Big problem whats the better default True or False?

**Comment by sliverc** [comment]
Such an option would certainly make sense... I would suggest default it to False as I would expect pure_check to not loose the memorized calls at garbage collector. And we are only talking about 3 which should be a big memory issue in most cases.

**Comment by ghost** [comment]
Thanks a lot!
